modLoader = "javafml"
loaderVersion = "[4,)"
license = "None"

[[mods]]
modId = "testmod"
version = "${version}"
displayName = "Test Mod"
authors = "Test"
description = '''
Test Mod for RangedWeaponAPI
'''

[[dependencies.testmod]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "ranged_weapon_api"
type = "required"
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"