modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/FabricExtras/RangedWeaponAPI/issues"
license = "MIT"

[[mods]]
modId = "ranged_weapon_api"
version = "${version}"
displayName = "RangedWeaponAPI"
authors = "Daedelus"
description = '''
Allows creating bows and crossbows, with just a few line of code
'''

[[dependencies.ranged_weapon_api]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ranged_weapon_api]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "ranged_weapon_api.mixins.json"
